import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

import Content from 'components/containers/content';
import LeftSidebar from 'components/containers/left-sidebar';
import Modal from 'components/containers/modal';
import Notification from 'components/containers/notification';
import Provider from 'components/containers/provider';
import QuickPanel from 'components/containers/quick-panel';
import {getServerUser} from 'lib/server-client';

import './globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'BASE',
  description: 'Generated by create next app',
};

export const runtime = 'edge';
export const dynamic = 'force-dynamic';
export const fetchCache = 'force-no-store';

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getServerUser();
  return (
    <html lang="en" data-theme="corporate">
      <body className={inter.className}>
        {!user ? (
          <>
            {/* Anon Layout */}
            {children}
          </>
        ) : (
          <Provider>
            {/* Authenticated Layout */}
            {/* Left drawer - containing page content and side bar (always open) */}
            <div className="drawer h-screen lg:drawer-open">
              <input
                id="left-sidebar-drawer"
                type="checkbox"
                className="drawer-toggle"
              />
              <Content>{children}</Content>
              <LeftSidebar />
            </div>

            {/* Right drawer - containing secondary content like notifications list etc.. */}
            <QuickPanel />

            {/* Modal layout container */}
            <Modal />

            {/** Notification layout container */}
            <Notification />
          </Provider>
        )}
      </body>
    </html>
  );
}
