name: Point of View Checker
on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request:
    types:
      - labeled
      - unlabeled
jobs:
  call-workflow:
    permissions:
      issues: write
      pull-requests: write
    uses: fox-hound-ltd/point-of-view-checker/.github/workflows/checker-workflow.yml@v1
