name: Build and Test
'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    runs-on: ${{ vars.SELF_HOSTED_RUNNER == 'true' && vars.RUNS_ON != '' && 'arc-runner-set' || 'ubuntu-latest' }}

    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
